### ISSUE TITLE
mining sleep seconds should be different each time

### ISSUE THREAD

**Issue by jarlah** [x-actly/Eve-Online-Mining-Bot#10]
Right now its doing this 

--- snip
sleeping 258.266......
--- snip
sleeping 258.266......
--- snip
sleeping 258.266......
--- snip

which is too predictable. It should add some variance and change into the sleep seconds.

**Comment by jarlah** [comment]
Nah. 250 is wrong. It should be 180-181 for strip lasers or 60-61 for normal lasers.

**Comment by sillychipmunk** [comment]
ignoring this issue.
