### ISSUE TITLE
Look into OCR for finding text with locations in screenshot

### ISSUE THREAD

**Issue by jarlah** [x-actly/Eve-Online-Mining-Bot#11]
ref https://github.com/sirfz/tesserocr?tab=readme-ov-file#advanced-api-examples

I think it can be used for finding Undock button at least. And maybe we could also use with together with right clicking in space to bring up the list of asteroid belts. etc

in practice it would mean taking a screenshot every time we need to go somewhere or find something on the screen. Which will not use too much ram if the images are discarded immediately after being processed by ocr

**Comment by x-actly** [comment]
This looks like an elegant solution, but I believe it far exceeds my abilities 😅

**Comment by jarlah** [comment]
Ill admit that most i do is figuring WHAT i want to make. Then i Ask chat gpt for details. As long as you know what you want and have a plan. Use AI 😊

**Comment by jarlah** [comment]
can also use https://pyautogui.readthedocs.io/en/latest/screenshot.html#the-locate-functions much simpler

**Comment by sillychipmunk** [comment]
Too complex and too little time ...
