### ISSUE TITLE
Consider removing cargo hold capacity 0.9 factor

### ISSUE THREAD

**Issue by jarlah** [x-actly/Eve-Online-Mining-Bot#17]
Its better to be full and hang a bit not mining than going home 90% full. Plus there is random sleeps built in.

**Comment by jarlah** [comment]
Been testing it and it seems better without the 0.9 factor

**Comment by x-actly** [comment]
Yeah, I'm with you on that, this factor can be removed. The decision to add this factor was from quite an early time when I started with the script. A lot of it just came from experimenting
