### ISSUE TITLE
Python Version not stated

### ISSUE THREAD

**Issue by zookeper** [x-actly/Eve-Online-Mining-Bot#2]
I have installed the latest version and several before that and im getting 

ERROR: Could not find a version that satisfies the requirement threading (from versions: none)
ERROR: No matching distribution found for threading

So what version satisfies this program?

**Comment by x-actly** [comment]
### Hi zookeper,

It seems there might be a misunderstanding regarding the "threading" module. "threading" is part of the Python standard library and typically does not require a separate installation. The error message you're encountering suggests that the "threading" module is not available as a separate installation package.

Please check the following:

1. **Correct Spelling:** Ensure that you are spelling the "threading" module correctly. It usually does not require a separate installation.

    ```bash
    pip install threading  # This line is likely not necessary for the "threading" module
    ```

2. **Python Version:** Make sure you are using the correct Python version. The "threading" module is part of the Python standard library and should be available without additional installation.

3. **Virtual Environment:** If you are using a virtual environment, make sure you are within it. Sometimes conflicts with global installations can occur.

4. **Module Conflicts:** Check if there are other modules with the name "threading" that might be causing conflicts.

If the issue persists, please provide more information, including your exact Python version, the operating system, and any additional error messages.

Thank you!
