### ISSUE TITLE
selecting window by pid and autofocus window ?

### ISSUE THREAD

**Issue by jarlah** [x-actly/Eve-Online-Mining-Bot#32]
Is it possible ? Can Python catch key strokes and mouse input if app is not visible ?

**Comment by x-actly** [comment]
Do you consider the possibility that all keyboard inputs and mouse interactions should only be executed within the Eve client?

**Comment by jarlah** [comment]
Actually i see now that pyautogui is running without focus and is capable of exexuting key strokes and mouse input while being not visible or out of focus. So this means the bot can make you select among a list of prosesses and then it will focus that process/window (bring it into foreground) periodically and before moving or typing. 

@x-actly nah i dont think so i just feel we need to be sure what window we are botting in. So forcing eve game client into focus by pid will solve this

**Comment by jarlah** [comment]
Been looking at bots framework written with Elm thats using memory reading. Someone needs to make a free open source solution for reading memory model in eve .... in rust maybe. Something low level and cross plattform
