### ISSUE TITLE
Keep Window on top and possibly change ui drastically

### ISSUE THREAD

**Issue by jarlah** [x-actly/Eve-Online-Mining-Bot#36]
We can use this to keep it on top https://stackoverflow.com/a/45064895

Then we can change how the ui looks. Make it a lot smaller, Find a better ux for small size. This will make it possible to run the eve game full screen 

Depends ofc on the fact that mouse and keyboard stuff outside "on top Windows" works as before

**Comment by sillychipmunk** [comment]
I dont think its any value of using time on UX 😂 for a bot i mean 😅
