### ISSUE TITLE
possible error with right click in safe spot

### ISSUE THREAD

**Issue by jarlah** [x-actly/Eve-Online-Mining-Bot#43]
@jarlah  there is also an error that does not give right click in the windows of eve online, I am trying to fix it

_Originally posted by @DesgerMadrigal in https://github.com/x-actly/Eve-Online-Mining-Bot/issues/28#issuecomment-2094446120_

**Comment by sillychipmunk** [comment]
this is definitely not an issue, at least not on windows. Feel free to reopen @DesgerMadrigal
