### ISSUE TITLE
Need to be able to disable shield hardener for mining in high sec

### ISSUE THREAD

**Issue by sillychipmunk** [x-actly/Eve-Online-Mining-Bot#47]
when you have 5 drones, you will never die in highsec other than by players

I think the most natural default is no shield hardener activation. We can make a section in readme for how to enable it

**Comment by x-actly** [comment]
wir sollten dennoch die möglichkeit hinzufügen, dass der bot zwei hardener aktivieren kann , falls jemand anti gank fit nutzen möchte mit procurer/skiff

**Comment by sillychipmunk** [comment]
look at commit https://github.com/x-actly/Eve-Online-Mining-Bot/pull/48/commits/f66c14e3b479451cad9681c6f9f558fda86ffbc1 in PR https://github.com/x-actly/Eve-Online-Mining-Bot/pull/48  ;) its no longer a "activate hardener thing". its more like a "activate whatever key combos you like when you leave station" .. so I should rename the config setting and variables .. suggestions ?
