### ISSUE TITLE
bug with global access to variable in mining operation ....

### ISSUE THREAD

**Issue by sillychipmunk** [x-actly/Eve-Online-Mining-Bot#52]

**Comment by sillychipmunk** [comment]
i thought it was fixed, but wasnt

**Comment by sillychipmunk** [comment]
finally its fixed. I think im beginning to get confident its usable in null/lows now btw @x-actly. But now, day job calls and now ill let this mining stuff run until reset at 11 utc. L8ter

**Comment by x-actly** [comment]
Anyway, treat yourself to a break; you've been churning out repositories one after another since last week!

**Comment by sillychipmunk** [comment]
dont worry about me. 

"you've been churning out repositories one after another since last week!"

churning out commits maybe ;)
