### ISSUE TITLE
Test release

### ISSUE THREAD

**Issue by sillychipmunk** [x-actly/Eve-Online-Mining-Bot#55]
@x-actly i made a draft release. Added windows and macos distributions made with pyinstaller. Can you test the windows one. Also add or change any text or even the version if you like, in the draft release

**Comment by x-actly** [comment]
I tested the release version with 15 runs last night. We can release the version whenever you're ready. I'll also make a new video for youtube over the weekend.

**Comment by sillychipmunk** [comment]
@x-actly released v0.2. I see in commit history you had iterated on v0.1.x etc

**Comment by sillychipmunk** [comment]
have no clue if macos dist will work on most macos versions or vice versa for windows. It will be interesting to test for sure

**Comment by sillychipmunk** [comment]
> I tested the release version with 15 runs last night. We can release the version whenever you're ready. I'll also make a new video for youtube over the weekend.

a new video will be awesome :D Maybe hard to show key strokes on video though. The ctrl-i stuff .. but you figure it out if you just use normal typing or something

**Comment by sillychipmunk** [comment]
Its not really syncing fast, Dropbox. But luckily there exists other options. Maybe in future we can add option to connect to dropbox via a library![image](https://github.com/x-actly/Eve-Online-Mining-Bot/assets/169029787/3cbcadf6-1c47-4b54-83f7-de5ba2f53740)

**Comment by sillychipmunk** [comment]
![image](https://github.com/x-actly/Eve-Online-Mining-Bot/assets/169029787/5bbd69d8-16e4-4eee-a963-a2440a702328)

**Comment by sillychipmunk** [comment]
> I tested the release version with 15 runs last night. We can release the version whenever you're ready. I'll also make a new video for youtube over the weekend.

btw when you make the video, you can use the windows distribution in the release right, to show its completely standalone, IF that is something you show in the video that is. Also you dont need to show the terminal anymore, since everything is logged and there is timers in the UI ;)

**Comment by sillychipmunk** [comment]
closing this.
