### ISSUE TITLE
Warping to belt time is too short in larger systems

### ISSUE THREAD

**Issue by x-actly** [x-actly/Eve-Online-Mining-Bot#62]
I'm considering whether to set the warp time via Combobox in the GUI or in the Config. Today, I tried mining in a nullsec system, and some of the mining anomalies were over 80 AU away. Or we change the function argument from sleep_and_log to LONG_SLEEP ?

**Comment by sillychipmunk** [comment]
we can maybe add some configuration for this. The more config the better. Optional config. right ? The less constants the better

**Comment by sillychipmunk** [comment]
with a reasonable default, of the current constants, normal high sec users will just see old behaviour. While advanced users can set warp to belt to a higher value (in seconds) in config

**Comment by sillychipmunk** [comment]
i suggesting keeping the gui as clean as possible and having support for advanced usage to the configuration file

**Comment by x-actly** [comment]
Yeah, that sounds good!

**Comment by sillychipmunk** [comment]
im actually taking a chill pill now, e.g. gaming a bit, so if you would like to try adding it, its mostly adding and using a new getter similar to another int getter like mining yield.

**Comment by x-actly** [comment]
I'll take a look at that once I've made the new video.

**Comment by sillychipmunk** [comment]
btw a bug in test buttons .. other than cargo reset all other test buttons are not saving config before testing
