### ISSUE TITLE
exit the bot properly when closing the window 

### ISSUE THREAD

**Issue by jarlah** [x-actly/Eve-Online-Mining-Bot#7]
plus the command line app wont close on ctrl-c

**Comment by sillychipmunk** [comment]
As we have in Java there should be an Exit "vm" when window closes

**Comment by jarlah** [comment]
fixed in https://github.com/x-actly/Eve-Online-Mining-Bot/commit/e2a760692369ea4b4e55394fdd5fa5aca13e5b0b
